version: "3.7"
services:
  chaperoo-frontend:
    image: andreatj/chaperoo-frontend:${app_version}
    build: .
    ports:
      - target: 81
        published: 81
    depends_on:
      - chaperoo-service
  chaperoo-service:
    image: jordangrindrod/chaperoo-service
    depends_on:
      - chaperoo-db
  chaperoo-db:
    image: jordangrindrod/chaperoo-db
    environment:
      - MYSQL_ROOT_PASSWORD="hello"
